### ISSUE TITLE
What is the difference between this legendary version and the Crystal version?

### ISSUE THREAD

**Issue by haoqoo** [JevLOMCN/mir1#1]
What is the difference between this legendary version and the Crystal version?

**Comment by Smir** [comment]
One is Mir 1, the other is Mir 2.

**Comment by JevLOMCN** [comment]
Hey, Carbon Mir 1 was built from the Crystal Mir 2 files.
If you have anymore questions feel free to drop a comment on our website [LOMCN](www.lomcn.net)
